replicaCount: 1

image:
  repository: rafaelvieira96/python-app-v2
  pullPolicy: IfNotPresent
  # tag: python-app-v2-dev-latest
  tag: latest

resources:
  requests:
    cpu: 40m
    memory: 40M